### PR TITLE
Remove reference to LitElement in lit-labs/motion

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
The animate controller should be compatible with any component implementing `ReactiveControllerHost` not only LitElement, see #2197

### CODE REVIEW

**Comment by leolorenzoluis** [comment]
@justinfagnani Thoughts?

**Comment by aomarks** [comment]
cc @sorvell

**Comment by RhondaP750** [comment]
I have no idea what any of this means, but I am trying to learn.

**Comment by justinfagnani** [comment]
I'm mostly ok with this. My one concern is that we don't find a need for having a LitElement host in the future.

Well, and that I have some doubts the usefulness of this change. This is a lit-html directive that only works if the host is a ReactiveElement. What other base classes besides LitElement meet that criteria? Did someone extend ReactiveElement to use lit-html, but not use LitElement? If so, I wonder why?

**Comment by OnurGumus** [comment]
Any updates for this?

**Review by augustjk — APPROVED** [review]
Sorry for taking so long to get to this. The changes here make sense.
I rebased to current main, resolving conflict, and added a changeset.
Thank you very much for the contribution!

**Pull request merged**
