### PR TITLE
Attempt at webcomponent community proposal to allow state update via "context protocol"

### PR DESCRIPTION
**Pull request by renoirb**
[proposal-community-protocol-context]: https://github.com/webcomponents/community-protocols/blob/c8c59e500d64eb32cb9f9b374cb6646041da9ac5/proposals/context.md
[community-protocols]: https://github.com/webcomponents/community-protocols

This is a draft PR, an attempt at making a library less state manager for DOM component updates and a lit adapter to update its state based on that protocol. That "*Context*" protocol is part of W3C’  [*Web Components* Community Group](https://web-components-cg.netlify.app/) [community-protocols][community-protocols] ([tracker](https://github.com/w3c/webcomponents-cg/issues))

[See proposal][proposal-community-protocol-context]

# Intent

This PR is an exploration for what's needed to have [**Context** protocol][proposal-community-protocol-context] in *lit-html*.

What would be great is to have a "no framework" dependency part, and an adapter that leverages it on the framework side, say what would be on *lit-html*. So, making a Svelte or Vue.js (or Web Component friendly framework) adapter would be just the basica specific to the framework.

# Related

* See also lit/lit#1955

### CODE REVIEW

**Comment by renoirb** [comment]
@googlebot I signed it!

**Comment by Westbrook** [comment]
Have you checked out this https://github.com/lit/lit/pull/1955? Seems like some room for shared effort... also, if you're interested in Community Protocols, we're having a session discussing them next week https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com the more insight the better!

**Comment by renoirb** [comment]
> Have you checked out this #1955? Seems like some room for shared effort (...)

No, I didn't know. I must have missed it.

Thanks for the info, i'll try to participate

**Comment by justinfagnani** [comment]
Thanks @renoirb, but closing as this went in with https://github.com/lit/lit/pull/1955

**Comment by renoirb** [comment]
Yup. No worries. In fact when I was talking here, the use-case I was working with at the time was exactly in the context of Micro frontends and verticals within a shell, like [described here](https://github.com/webcomponents-cg/community-protocols/issues/19#issuecomment-909464296), and I was trying to explain that, but I couldn't get to say that.

**Pull request closed without merging**
