### PR TITLE
[lit/lit-starter-ts] fix: 🐛 missing pnpm dependencies

### PR DESCRIPTION
**Pull request by melMass**
Migrated from https://github.com/lit/lit-element-starter-ts/pull/87

Simple PR to fix the pnpm dependencies errors:

```log
Error while transforming node_modules/lit/index.js: 
Could not resolve import "@lit/reactive-element".

Error while transforming node_modules/lit/decorators.js: 
Could not resolve import "@lit/reactive-element/decorators/custom-element.js".

Error while transforming node_modules/lit/index.js: 
Could not resolve import "lit-element/lit-element.js".
```

### CODE REVIEW

**Comment by bicknellr** [comment]
This package's non-test files only import from `lit`, which is already listed as a dependency:

https://github.com/lit/lit/blob/520b47132af8e21868df5dc4dfdf5e003a38d158/packages/lit-starter-ts/package.json#L44

and `lit` already lists all of these here:

https://github.com/lit/lit/blob/520b47132af8e21868df5dc4dfdf5e003a38d158/packages/lit/package.json#L351-L353

Have you tried a clean install?

**Comment by melMass** [comment]
I will check again but I believe I had the issue on first run:
- clone
- pnpm i 
- pnmp dev

**Comment by justinfagnani** [comment]
@melMass any updates here? Is this still relevant?

**Comment by raymondboswel** [comment]
I still get this with a freshly cloned copy of the starter template. 
npm i
terminal 1: npm run build
terminal 2: npm run serve

```
Web Dev Server started...

  Root dir: /home/raymond/git/lit-element-starter-ts
  Local:    http://localhost:8000/
  Network:  http://192.168.5.76:8000/

Error while transforming node_modules/lit/index.js: Could not resolve import "@lit/reactive-element".

> 1 | import"@lit/reactive-element";import"lit-html";export*from"lit-element/lit-element.js";export*from"lit-html/is-server.js";
    |       ^
  2 | //# sourceMappingURL=index.js.map
  3 |

```

**Comment by justinfagnani** [comment]
@raymondboswel 

> The workaround is to run npm i @lit/reactive-element lit-html lit-element

This really shouldn't be necessary, since `lit` already depends on `@lit/reactive-element`, etc. Something is breaking in the install.

Can you relay your npm version, OS, and `npm ls` output when the project is in the broken state?

**Comment by raymondboswel** [comment]
I tried with both pnpm and npm (deleting node_modules in between) with the same result. 

npm ls: 
```
@lit/lit-starter-ts@2.0.2 /home/raymond/git/lit-element-starter-ts
├── @11ty/eleventy-plugin-syntaxhighlight@4.2.0
├── @11ty/eleventy@1.0.2
├── @custom-elements-manifest/analyzer@0.6.9
├── @lit/reactive-element@2.0.4
├── @open-wc/testing@4.0.0
├── @rollup/plugin-node-resolve@15.2.3
├── @rollup/plugin-replace@5.0.7
├── @rollup/plugin-terser@0.4.4
├── @types/mocha@10.0.7
├── @typescript-eslint/eslint-plugin@5.62.0
├── @typescript-eslint/parser@5.62.0
├── @web/dev-server-legacy@1.0.3
├── @web/dev-server@0.1.38
├── @web/test-runner-playwright@0.9.0
├── @web/test-runner@0.15.3
├── @webcomponents/webcomponentsjs@2.8.0
├── eslint@8.57.0
├── lit-analyzer@1.2.1
├── lit-element@4.1.0
├── lit-html@3.2.0
├── lit@3.2.0
├── prettier@2.8.8
├── rimraf@3.0.2
├── rollup-plugin-summary@2.0.1
├── rollup@4.21.2
└── typescript@5.5.4
```

npm version: 10.5.2

OS: Manjaro (Arch linux distro)

If this doesn't affect anyone else than I'm happy to stick with the workaround :)

**Comment by justinfagnani** [comment]
That shows `@lit/reactive-element`, `lit-element`, and `lit-html` all installed. I can't see why imports from `lit` into those wouldn't be working.

This must be a bug in `@web/dev-server`. The version in here is pretty old.

**Comment by raymondboswel** [comment]
My apologies, I just realized I posted the `npm ls` output of the 'fixed' version. Here's the output of a freshly cloned copy:
```
npm ls                                                                                                                                         ✔  1m 23s  
@lit/lit-starter-ts@2.0.2 /home/raymond/temp/lit-element-starter-ts
├── @11ty/eleventy-plugin-syntaxhighlight@4.2.0
├── @11ty/eleventy@1.0.2
├── @custom-elements-manifest/analyzer@0.6.9
├── @open-wc/testing@4.0.0
├── @rollup/plugin-node-resolve@15.2.3
├── @rollup/plugin-replace@5.0.7
├── @rollup/plugin-terser@0.4.4
├── @typescript-eslint/eslint-plugin@5.62.0
├── @typescript-eslint/parser@5.62.0
├── @web/dev-server-legacy@1.0.3
├── @web/dev-server@0.1.38
├── @web/test-runner-playwright@0.9.0
├── @web/test-runner@0.15.3
├── @webcomponents/webcomponentsjs@2.8.0
├── eslint@8.57.0
├── lit-analyzer@1.2.1
├── lit@3.2.0
├── prettier@2.8.8
├── rimraf@3.0.2
├── rollup-plugin-summary@2.0.1
├── rollup@4.21.2
└── typescript@5.5.4

```

**Pull request closed without merging**
