### PR TITLE
Add dark theme version of the Lit logo for GitHub READMEs

### PR DESCRIPTION
**Pull request by aomarks**
As of just now, GitHub supports showing a different image for light vs dark theme: https://twitter.com/ashtom/status/1463554157932023808

This adds a new dark theme version of the logo, which is the same except that the Lit text is white, and uses the new `#gh-light-mode-only` and `#gh-dark-mode-only` fragments to switch between them.

This also updates the logo to the new more compact version of the logo SVG from https://github.com/lit/lit.dev/pull/578.

Fixes https://github.com/lit/lit/issues/2296

### CODE REVIEW

**Comment by aomarks** [comment]
@justinfagnani: This is going to churn the `lit` package again, since I updated the logo to the new more compact version. The original reason we added the logo to the NPM package was so that it would show up on npmjs.com -- but then we learned that npmjs.com doesn't actually read those images from relative paths, it finds images from GitHub automatically. **So should we instead remove the logo from the NPM package, to save the bytes?**

**Comment by aomarks** [comment]
Hmm, I guess a downside of this is that the version on npmjs.com is going to show both images, since it doesn't know about the special fragments.

I guess we could run a script that removes the dark mode version before we publish to NPM.

**Comment by aomarks** [comment]
> Hmm, I guess a downside of this is that the version on npmjs.com is going to show both images, since it doesn't know about the special fragments.

Sounds like NPM and VS Code will both support this too eventually https://twitter.com/ashtom/status/1463567599246065666

**Comment by justinfagnani** [comment]
Until npm supports this, could we add a white stroke/border/background to the logo image to make it work in both?

**Comment by graynorton** [comment]
I consulted Ocupop on this topic before the holidays and they did some exploration, eventually concluding that they weren't happy with the white stroke / border solution from a visual brand integrity point of view.

Their recommendation was to use the dark-mode-compatible version of the logo if we have the ability to switch, and to use a white rectangular background if we don't:

https://gyazo.com/18b45a5c99da57a77235c2a7337f5fd3

**Comment by justinfagnani** [comment]
@aomarks do we know if npm supports the dark mode image convention yet?

**Comment by augustjk** [comment]
Superseded by https://github.com/lit/lit/pull/3457

**Pull request closed without merging**
