### PR TITLE
Add missing await in task.ts

### PR DESCRIPTION
**Pull request by rictic**
Flagged by a linter, was leaving this off intentional?

### CODE REVIEW

**Review by AndrewJakubowicz — APPROVED** [review]
It doesn't look like this would change any behavior - as `performTask` is called in `hostUpdated` without awaiting.

**Comment by justinfagnani** [comment]
`performTask()` is public, so this matters. We just don't have any test coverage of calling `performTask()` directly.

@rictic it'd be nice to get a test for this. I think one that calls `await performTask()` and checks that some state was updated in the task function on the next line should suffice.

**Comment by rictic** [comment]
performTask is protected, and only called by hostUpdated, and hostUpdated does not return the promise ,so this would be difficult to observe

**Comment by AndrewJakubowicz** [comment]
This could be a breaking change for any user extending `performTask` and awaiting on `performTask` - although it seems like better behavior to make it possible to `await` the run task.

Agree about adding a test.

**Pull request merged**
