### PR TITLE
Update package locks from npm run nuke

### PR DESCRIPTION
**Pull request by e111077**
Kept running into issues from a fresh clone regarding some lockfile in playwright. Locally could fix it by running `npx lerna bootstrap` because the issue kept reproducing with `lerna bootstrap --ci`. Attempting a package lock update to dee if this fixes the issue

error encountered:

```
lerna ERR! npm ci exited 1 in '@lit/localize'
lerna ERR! npm ci stderr:
npm ERR! code 1
npm ERR! path /Users/emarquez/Workspace/lit/lit/packages/localize/node_modules/playwright
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/emarquez/Workspace/lit/lit/packages/localize/node_modules/proper-lockfile/lib/lockfile.js:68
npm ERR!                 return callback(Object.assign(new Error('Lock file is already being held'), { code: 'ELOCKED', file }));
npm ERR!                                               ^
npm ERR! 
npm ERR! Error: Lock file is already being held
npm ERR!     at /Users/emarquez/Workspace/lit/lit/packages/localize/node_modules/proper-lockfile/lib/lockfile.js:68:47
npm ERR!     at callback (/Users/emarquez/Workspace/lit/lit/packages/localize/node_modules/graceful-fs/polyfills.js:299:20)
npm ERR!     at FSReqCallback.oncomplete (node:fs:199:5) {
npm ERR!   code: 'ELOCKED',
npm ERR!   file: '/Users/emarquez/Library/Caches/ms-playwright'
npm ERR! }
npm ERR! 
npm ERR! Node.js v17.4.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/emarquez/.npm/_logs/2022-04-19T23_06_45_563Z-debug-0.log
lerna ERR! npm ci exited 1 in '@lit/localize'
```

### CODE REVIEW

**Comment by e111077** [comment]
Can confirm this worked. How should I proceed with the changeset? Does this even require a version bump?

**Comment by aomarks** [comment]
> Can confirm this worked. How should I proceed with the changeset? Does this even require a version bump?

You can do `npx changeset --empty`. `package-lock.json` files are never published, so it can't affect anybody other than us, so it doesn't need to be in the changelog.

**Review by justinfagnani — APPROVED** [review]
🎉

**Comment by justinfagnani** [comment]
This looks great, so I'm going to merge right away

**Pull request merged**
