### PR TITLE
Release rc2

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Review by kevinpschaaf — APPROVED** [review]

**Comment by abdonrd** [comment]
@rictic this release is not published at npm.

**Comment by rictic** [comment]
This only included a release of lit-html to add TypeScript typings for trusted types

**Comment by Artur-** [comment]
If you want external testers to test that version, please release a new `lit` rc2 also

**Comment by abdonrd** [comment]
> This only included a release of lit-html to add TypeScript typings for trusted types

Yeah, I know it! But our build fail for this types.

**Comment by justinfagnani** [comment]
@Artur- you don't need to bump a dependency for npm to pick up the latest version if it's within semver range.

On a new install:

```sh
> npm i lit
> npm ls lit-html
└─┬ lit@2.0.0-rc.1
  ├─┬ lit-element@3.0.0-rc.1
  │ └── lit-html@2.0.0-rc.2 deduped
  └── lit-html@2.0.0-rc.2
```

@abdonrd what exactly is failing?

**Comment by abdonrd** [comment]
> @abdonrd what exactly is failing?

The lit-analyzer:

Screenshot 2021-04-23 at 18 11 51

**Comment by justinfagnani** [comment]
@abdonrd I just created a new project and get no errors. Can you open a new issue so we can discuss there?

**Pull request merged**
