### PR TITLE
[lit/react] Fix event binding erroneously being set on custom element instance

### PR DESCRIPTION
**Pull request by augustjk**
Fixes https://github.com/lit/lit/issues/4569

We now correctly early return when an event prop binding contains the same value across re-renders, instead of moving on to setting it on the underlying element instance.

### CODE REVIEW

**Review by justinfagnani — APPROVED** [review]
nice! 🎉

**Comment by augustjk** [comment]
Benchmarks workflow failure should be fixed by https://github.com/lit/lit/pull/4573

**Review by stefanpearson — APPROVED** [review]
Amazing! I didn't expect a fix so quickly, you outpaced my workaround PR. I'm also glad I'm, in fact, not insane. 🙌

**Comment by stefanpearson** [comment]
Hey @augustjk 👋 , what is the release schedule for pushing out a new version?

**Comment by augustjk** [comment]
@stefanpearson Sorry for the delay. It has just now been published!

**Comment by stefanpearson** [comment]
> @stefanpearson Sorry for the delay. It has just now been published!

Thanks!

**Pull request merged**
