### PR TITLE
Remove subpath folder mapping from packages' `exports` field.

### LINKED ISSUE #1882: [SSR] Deprecated exports folder mapping notice when import lit with Node 16
Importing `lit` with Node v16 displays a deprecation notice about our `exports` field folder mappings in the lit packages.

Repro:
(Note this requires Node 16+)
```
cd packages labs/ssr
npm run start
```

Result:
```
(node:19711) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./decorators/" in the "exports" field module resolution of the package at /home/aomarks/work/lit/packages/labs/ssr/node_modules/lit/package.json imported from /home/aomarks/work/lit/packages/labs/ssr/demo/global/module.js.
Update this package.json to use a subpath pattern like "./decorators/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:19711) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./directives/" in the "exports" field module resolution of the package at /home/aomarks/work/lit/packages/labs/ssr/node_modules/@lit-labs/ssr-client/package.json imported from /home/aomarks/work/lit/packages/labs/ssr/lib/render-lit-html.js.
Update this package.json to use a subpath pattern like "./directives/*".
(node:19711) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./decorators/" in the "exports" field module resolution of the package at /home/aomarks/work/lit/packages/lit/node_modules/@lit/reactive-element/package.json imported from /home/aomarks/work/lit/packages/lit/decorators/property.js.
Update this package.json to use a subpath pattern like "./decorators/*".
Server listening on port 8080
```

According to https://nodejs.org/api/packages.html#packages_subpath_folder_mappings it looks like we now need to use `/*` instead of `/` when specifying a subpath in our `exports` field.

E.g. this section https://github.com/lit/lit/blob/576cde17734c93a18d0ebf07d83b87ff749f1de5/packages/lit/package.json#L25 needs to change to something like:

```js
"./decorators/*": {
  "default": "./decorators/*.js"
},
```

- I'm not sure if this works recursively, or if we need to enumerate any subfolders too
- We'll need to make sure @web/dev-server, Rollup, Webpack, and any other important tools understand this new syntax before we change it.

cc @justinfagnani @kevinpschaaf

### PR DESCRIPTION
**Pull request by bicknellr**
Fixes #1882.

### CODE REVIEW

**Comment by bicknellr** [comment]
I should have left this as a draft: I need to test this out with the tools listed in the issue.

**Review by justinfagnani — APPROVED** [review]
🎉

**Comment by justinfagnani** [comment]
> I need to test this out with the tools listed in the issue

I think if our starter kits work in prod and dev mode that this is fine. It doesn't use the new subfolder path syntax, just the already existing file mappings. So nothing should newly break with this and it prevents some invalid imports.

**Comment by bicknellr** [comment]
> > I need to test this out with the tools listed in the issue
> 
> I think if our starter kits work in prod and dev mode that this is fine. It doesn't use the new subfolder path syntax, just the already existing file mappings. So nothing should newly break with this and it prevents some invalid imports.

(repeating a bit from chat...) I updated `@web/dev-server` in the starter projects to test this because the version in `main` depends on an older version of `@rollup/plugin-node-resolve` that doesn't support `exportConditions`. With this update, you can replace the `nodeResolve: true,` in those packages' `web-dev-server.config.js` with `nodeResolve: {exportConditions: ['development']},` to see the dev-mode sources.

**Review by justinfagnani — APPROVED** [review]

**Comment by kevinpschaaf** [comment]
Note `main` now has the updated web-dev-server as well, so now that this branch is merged with main to eliminate other conflicts, that no longer shows up as a diff.

**Comment by kevinpschaaf** [comment]
Note I added support for the `MODE=dev` / `MODE=prod` environment variable control over WTR / WDS's node module resolution, along with commands for running test & serve in prod mode (now dev by default). @justinfagnani PTAL

**Review by justinfagnani — APPROVED** [review]
LGTM with new changes

**Pull request merged**
