### PR TITLE
Upgrade build targets to ES2021

### PR DESCRIPTION
**Pull request by justinfagnani**
I did this across the board: TypeScript target and lib, and Terser `ecma` setting, for all packages and tools tsconfigs. This might be a bit aggressive, but I want to see if this works.

### CODE REVIEW

**Review by rictic — APPROVED** [review]

**Comment by augustjk** [comment]
Maybe we should drop this line from `CONTRIBUTING.md` since we actually do downlevel
https://github.com/lit/lit/blob/21e22cccf0bbac4147139041c5247b4a4846b524/CONTRIBUTING.md?plain=1#L64

**Review by augustjk — APPROVED** [review]

**Comment by abdonrd** [comment]
Looking at this... Wouldn't it help to have a shared `tsconfig.json` between most packages?

**Comment by augustjk** [comment]
> Looking at this... Wouldn't it help to have a shared `tsconfig.json` between most packages?

We totally do this for the lit/lit.dev repo. Maybe we should consider that for here too.

**Comment by justinfagnani** [comment]
Maybe, but not in this PR. Let's keep this as simple as possible.

**Pull request merged**
