### PR TITLE
Use Lit Robot's info as the global name and email for git operations during releases.

### PR DESCRIPTION
**Pull request by bicknellr**
This PR sets the global git email and name to those of our robot account so that it doesn't have to be set in each individual repo before committing.

### CODE REVIEW

**Review by aomarks — APPROVED** [review]

**Comment by aomarks** [comment]
Cool! Maybe this will fix https://github.com/lit/lit/issues/2502

**Comment by justinfagnani** [comment]
This is draft... is it intended for review?

**Comment by bicknellr** [comment]
> Cool! Maybe this will fix #2502

Huh, maybe!

> This is draft... is it intended for review?

I didn't mark it as ready since it's based on #2496, which is still pending, but I certainly won't stop you if you want to look it over early

**Comment by bicknellr** [comment]
Actually no... I'd rather see that other PR work without changing the existing git setup.

**Comment by bicknellr** [comment]
Closing: this was added as part of #2540.

**Pull request closed without merging**
