### PR TITLE
fix: ts issue with `moduleResolution: NodeNext`

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by justinfagnani** [comment]
Thanks! Looks good, but we need a changeset file. Run `npm run changeset`, choose the lit package, and write a description of the chage.

**Review by justinfagnani — COMMENTED** [review]
_deleted_

**Review by justinfagnani — CHANGES_REQUESTED** [review]
Please add a changeset

**Comment by augustjk** [comment]
Thanks for original contribution. This PR is no longer needed with #3320 merged, as we needed the types to point to those in the `development` directory instead of the package root.

**Pull request closed without merging**
